version: "3"
services:
  production:
    build:
      dockerfile: ./environments/production/Dockerfile
    image: terraform:production
    env_file: .env
    volumes:
      - ./environments/production:/terraform/environments/production
      - ./modules:/terraform/modules
  backend:
    build:
      dockerfile: ./environments/backend/Dockerfile
    image: terraform:backend
    env_file: .env
    volumes:
      - ./environments/backend:/terraform/environments/backend
      - ./modules:/terraform/modules